import { useEffect, useMemo, useState } from 'react'
import type { FormEvent } from 'react'
import type { Session } from '@supabase/supabase-js'
import type { LucideIcon } from 'lucide-react'
import { AlertTriangle, ArrowRight, Bike, CalendarDays, Check, CheckCircle2, ChevronRight, CircleGauge, Clock3, Cloud, Ellipsis, Gauge, History as HistoryIcon, LogOut, Menu, Pencil, Plus, Settings2, ShieldCheck, Sparkles, Trash2, Wrench, X } from 'lucide-react'
import { toast, Toaster } from 'sonner'
import './App.css'
import { Avatar, AvatarFallback } from '@/components/ui/avatar'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog'
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from '@/components/ui/dropdown-menu'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Separator } from '@/components/ui/separator'
import { Skeleton } from '@/components/ui/skeleton'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Textarea } from '@/components/ui/textarea'
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip'
import { deleteRecord, loadCloudData, saveItem, saveMotorcycle, saveRecord } from './data'
import { formatMoney, getStatus, type MaintenanceItem, type MaintenanceRecord, type Motorcycle } from './domain'
import { supabase } from './lib/supabase'

const today = new Date().toISOString().slice(0, 10)
type View = 'overview' | 'history' | 'settings'
type LogTarget = { itemId: string; record?: MaintenanceRecord }
const statusMeta = {
  overdue: { label: 'Overdue', icon: AlertTriangle, className: 'status-overdue' }, due: { label: 'Due now', icon: Clock3, className: 'status-due' }, due_soon: { label: 'Due soon', icon: Clock3, className: 'status-soon' }, up_to_date: { label: 'Up to date', icon: CheckCircle2, className: 'status-good' }, condition_based: { label: 'Inspect', icon: ShieldCheck, className: 'status-check' }, needs_baseline: { label: 'Set baseline', icon: CircleGauge, className: 'status-muted' },
} as const

function App() {
  const [session, setSession] = useState<Session | null>(null), [authReady, setAuthReady] = useState(!supabase)
  const [bike, setBike] = useState<Motorcycle | null>(null), [items, setItems] = useState<MaintenanceItem[]>([]), [records, setRecords] = useState<MaintenanceRecord[]>([]), [motorcycleId, setMotorcycleId] = useState(''), [dataUserId, setDataUserId] = useState('')
  const [view, setView] = useState<View>('overview'), [logTarget, setLogTarget] = useState<LogTarget | null>(null), [deleteTarget, setDeleteTarget] = useState<MaintenanceRecord | null>(null)
  useEffect(() => {
    if (!supabase) return
    supabase.auth.getSession().then(({ data }) => { setSession(data.session); setAuthReady(true) })
    const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, next) => setSession(next))
    return () => subscription.unsubscribe()
  }, [])
  useEffect(() => {
    if (!session) return
    let active = true
    loadCloudData(session.user.id).then((data) => { if (!active) return; setBike(data.motorcycle); setItems(data.items); setRecords(data.records); setMotorcycleId(data.motorcycle.id); setDataUserId(session.user.id) }).catch((error: Error) => toast.error('Could not load your garage', { description: error.message }))
    return () => { active = false }
  }, [session])
  const statuses = useMemo(() => bike ? items.map((item) => ({ item, result: getStatus(item, records, bike, today) })) : [], [items, records, bike])
  const counts = statuses.reduce<Record<string, number>>((all, row) => { all[row.result.status] = (all[row.result.status] ?? 0) + 1; return all }, {})
  async function handleRecordSave(record: MaintenanceRecord) {
    if (!session || !motorcycleId) return
    await saveRecord(session.user.id, motorcycleId, record)
    setRecords((current) => [record, ...current.filter((entry) => entry.id !== record.id)]); setLogTarget(null)
    toast.success(logTarget?.record ? 'Maintenance entry updated' : 'Maintenance logged', { description: 'Your changes are saved to Supabase.' })
  }
  async function handleDelete() {
    if (!deleteTarget) return
    try { await deleteRecord(deleteTarget.id); setRecords((current) => current.filter((record) => record.id !== deleteTarget.id)); toast.success('Entry deleted') }
    catch (error) { toast.error('Could not delete entry', { description: error instanceof Error ? error.message : 'Try again.' }) }
    finally { setDeleteTarget(null) }
  }
  if (!authReady) return <LoadingScreen />
  if (!supabase) return <ConfigurationScreen />
  if (!session) return <AuthScreen />
  if (!bike || dataUserId !== session.user.id) return <LoadingScreen />
  const urgent = statuses.filter(({ result }) => ['overdue', 'due', 'due_soon', 'needs_baseline'].includes(result.status))
  const initials = session.user.email?.slice(0, 2).toUpperCase() ?? 'AL'
  return <TooltipProvider><div className="app-shell">
    <header className="topbar"><div className="topbar-inner"><Brand /><div className="topbar-actions"><Badge variant="outline" className="sync-badge"><Cloud /> Supabase synced</Badge><DropdownMenu><DropdownMenuTrigger render={<Button variant="ghost" size="icon" className="account-button" aria-label="Account menu" />}><Avatar><AvatarFallback>{initials}</AvatarFallback></Avatar></DropdownMenuTrigger><DropdownMenuContent align="end" className="account-menu"><div className="account-email">Signed in as<br /><strong>{session.user.email}</strong></div><DropdownMenuSeparator /><DropdownMenuItem onClick={() => supabase?.auth.signOut()}><LogOut /> Sign out</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></div></header>
    <main className="main-content"><section className="welcome-row"><div><p className="eyebrow">{new Date().toLocaleDateString('en-MY', { weekday: 'long', day: 'numeric', month: 'long' })}</p><h1>Your ride, ready.</h1><p className="lede">A clear view of what your ADV needs next.</p></div><Button size="lg" className="primary-cta" onClick={() => setLogTarget({ itemId: items[0]?.id ?? '' })} disabled={!items.length}><Plus /> Log maintenance</Button></section>
      <BikeHero bike={bike} onEdit={() => setView('settings')} />
      <Tabs value={view} onValueChange={(next) => setView(next as View)}><div className="nav-row"><TabsList><TabsTrigger value="overview"><CircleGauge /> Overview</TabsTrigger><TabsTrigger value="history"><HistoryIcon /> History <span className="tab-count">{records.length}</span></TabsTrigger><TabsTrigger value="settings"><Settings2 /> Settings</TabsTrigger></TabsList><DropdownMenu><DropdownMenuTrigger render={<Button variant="outline" size="icon" className="mobile-nav" aria-label="Open navigation" />}><Menu /></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={() => setView('overview')}><CircleGauge /> Overview</DropdownMenuItem><DropdownMenuItem onClick={() => setView('history')}><HistoryIcon /> History</DropdownMenuItem><DropdownMenuItem onClick={() => setView('settings')}><Settings2 /> Settings</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div>
        <TabsContent value="overview"><Overview statuses={statuses} counts={counts} urgent={urgent} onLog={(itemId) => setLogTarget({ itemId })} /></TabsContent>
        <TabsContent value="history"><HistoryView records={records} items={items} onAdd={() => setLogTarget({ itemId: items[0]?.id ?? '' })} onEdit={(record) => setLogTarget({ itemId: record.itemId, record })} onDelete={setDeleteTarget} /></TabsContent>
        <TabsContent value="settings"><SettingsView bike={bike} items={items} userId={session.user.id} motorcycleId={motorcycleId} onSaved={(nextBike, nextItems) => { setBike(nextBike); setItems(nextItems) }} /></TabsContent>
      </Tabs></main>
    {logTarget && <LogDialog open target={logTarget} items={items} bike={bike} onOpenChange={(open) => !open && setLogTarget(null)} onSave={handleRecordSave} />}
    <DeleteDialog record={deleteTarget} item={items.find((item) => item.id === deleteTarget?.itemId)} onOpenChange={(open) => !open && setDeleteTarget(null)} onConfirm={handleDelete} /><Toaster position="bottom-center" richColors closeButton />
  </div></TooltipProvider>
}

function Brand() { return <div className="brand"><div className="brand-mark"><Wrench /></div><div><strong>ADV Log</strong><span>Maintenance, made simple</span></div></div> }
function LoadingScreen() { return <div className="loading-screen"><div className="loading-card"><Brand /><div className="loading-stack"><Skeleton className="h-7 w-52" /><Skeleton className="h-4 w-72 max-w-full" /><Skeleton className="h-32 w-full" /></div></div></div> }
function ConfigurationScreen() { return <div className="auth-screen"><Card className="auth-card"><CardHeader><div className="brand-mark"><Wrench /></div><CardTitle>Connect Supabase</CardTitle><CardDescription>Add VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY to start ADV Log.</CardDescription></CardHeader></Card></div> }
function AuthScreen() {
  const [email, setEmail] = useState(''), [password, setPassword] = useState(''), [reset, setReset] = useState(false), [submitting, setSubmitting] = useState(false)
  async function submit(event: FormEvent) { event.preventDefault(); if (!supabase) return; setSubmitting(true); if (reset) { const { error } = await supabase.auth.resetPasswordForEmail(email, { redirectTo: window.location.origin }); if (error) toast.error('Could not send reset email', { description: error.message }); else toast.success('Check your inbox', { description: 'Password reset instructions are on the way.' }) } else { const { error } = await supabase.auth.signInWithPassword({ email, password }); if (error) toast.error('Could not sign in', { description: error.message }) } setSubmitting(false) }
  return <TooltipProvider><div className="auth-screen"><div className="auth-layout"><div className="auth-story"><Brand /><div><Badge><Sparkles /> Built for the next ride</Badge><h1>Know what’s due.<br />Ride with confidence.</h1><p>Your maintenance history and service schedule, securely synced in one calm place.</p></div><div className="auth-proof"><ShieldCheck /><span><strong>Private by default</strong>Your records are protected by Supabase authentication.</span></div></div><Card className="auth-card"><CardHeader><CardTitle>{reset ? 'Reset your password' : 'Welcome back'}</CardTitle><CardDescription>{reset ? 'We’ll email you a secure reset link.' : 'Sign in to open your garage.'}</CardDescription></CardHeader><CardContent><form onSubmit={submit} className="form-stack"><div className="field"><Label htmlFor="email">Email address</Label><Input id="email" type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@example.com" required /></div>{!reset && <div className="field"><Label htmlFor="password">Password</Label><Input id="password" type="password" autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} required /></div>}<Button size="lg" type="submit" disabled={submitting}>{submitting ? 'Please wait…' : reset ? 'Send reset link' : 'Sign in'} <ArrowRight /></Button><Button variant="ghost" type="button" onClick={() => setReset((value) => !value)}>{reset ? 'Back to sign in' : 'Forgot password?'}</Button></form></CardContent></Card></div><Toaster position="bottom-center" richColors /></div></TooltipProvider>
}

function BikeHero({ bike, onEdit }: { bike: Motorcycle; onEdit: () => void }) { return <Card className="bike-hero"><CardContent><div className="bike-visual"><div className="visual-grid" /><Badge variant="secondary"><Bike /> Your motorcycle</Badge><div className="adv-type"><span>ADV</span><small>{bike.model.replace(/\D/g, '') || '150'}</small></div></div><div className="bike-details"><div className="bike-title-row"><div><p className="eyebrow">Your motorcycle</p><h2>{bike.name}</h2><p>{bike.make} {bike.model} · Tracking since {bike.startDate ? new Date(`${bike.startDate}T12:00:00`).toLocaleDateString('en-MY', { month: 'short', year: 'numeric' }) : 'not set'}</p></div><Tooltip><TooltipTrigger render={<Button variant="ghost" size="icon" onClick={onEdit} aria-label="Edit motorcycle" />}><Pencil /></TooltipTrigger><TooltipContent>Edit motorcycle</TooltipContent></Tooltip></div><Separator /><div className="odometer"><span><Gauge /> Current odometer</span><strong>{bike.currentOdometerKm.toLocaleString()} <small>km</small></strong></div></div></CardContent></Card> }
function Overview({ statuses, counts, urgent, onLog }: { statuses: Array<{ item: MaintenanceItem; result: ReturnType<typeof getStatus> }>; counts: Record<string, number>; urgent: Array<{ item: MaintenanceItem; result: ReturnType<typeof getStatus> }>; onLog: (itemId: string) => void }) {
  const summary = [{ label: 'Overdue', value: counts.overdue ?? 0, icon: AlertTriangle, tone: 'red' }, { label: 'Coming up', value: (counts.due ?? 0) + (counts.due_soon ?? 0), icon: Clock3, tone: 'amber' }, { label: 'Up to date', value: counts.up_to_date ?? 0, icon: CheckCircle2, tone: 'green' }, { label: 'Condition checks', value: counts.condition_based ?? 0, icon: ShieldCheck, tone: 'blue' }]
  const condition = statuses.filter(({ result }) => result.status === 'condition_based')
  return <div className="content-stack"><section className="summary-grid">{summary.map((card) => <SummaryCard key={card.label} {...card} />)}</section><MaintenanceSection title="Next actions" description="Prioritised from your latest records and odometer." count={urgent.length} rows={urgent} empty="Nothing urgent. Your service schedule is in good shape." onLog={onLog} /><MaintenanceSection title="Condition checks" description="Quick inspections that keep every ride safe." rows={condition} onLog={onLog} /></div>
}
function SummaryCard({ label, value, icon: Icon, tone }: { label: string; value: number; icon: LucideIcon; tone: string }) { return <Card className={`summary-card tone-${tone}`}><CardContent><span className="summary-icon"><Icon /></span><div><strong>{value}</strong><span>{label}</span></div></CardContent></Card> }
function MaintenanceSection({ title, description, count, rows, empty, onLog }: { title: string; description: string; count?: number; rows: Array<{ item: MaintenanceItem; result: ReturnType<typeof getStatus> }>; empty?: string; onLog: (itemId: string) => void }) { return <section><div className="section-heading"><div><h2>{title}</h2><p>{description}</p></div>{count !== undefined && <Badge variant="outline">{count} {count === 1 ? 'item' : 'items'}</Badge>}</div><Card className="maintenance-list"><CardContent>{rows.length ? rows.map(({ item, result }) => <MaintenanceRow key={item.id} item={item} result={result} onClick={() => onLog(item.id)} />) : <div className="empty-state"><CheckCircle2 /><div><strong>All caught up</strong><span>{empty}</span></div></div>}</CardContent></Card></section> }
function MaintenanceRow({ item, result, onClick }: { item: MaintenanceItem; result: ReturnType<typeof getStatus>; onClick: () => void }) {
  const info = statusMeta[result.status], Icon = info.icon
  const detail = result.status === 'overdue' ? item.basis === 'time' ? `${Math.abs(result.days ?? 0)} days overdue` : `${Math.abs(result.remaining ?? 0).toLocaleString()} km overdue` : result.status === 'due' ? 'Due today' : result.status === 'due_soon' ? item.basis === 'time' ? `Due in ${result.days} days` : `Due in ${result.remaining?.toLocaleString()} km` : item.basis === 'condition' ? 'Inspect before your next long ride' : 'No action needed'
  const schedule = item.basis === 'time' ? `Every ${item.intervalMonths} months` : item.basis === 'distance' ? `Every ${item.intervalKm?.toLocaleString()} km` : 'Condition-based'
  return <Button variant="ghost" className="maintenance-row" onClick={onClick}><span className={`row-icon ${info.className}`}><Icon /></span><span className="row-copy"><strong>{item.name}</strong><span>{schedule}</span></span><span className={`row-status ${info.className}`}><Badge variant="outline">{info.label}</Badge><small>{detail}</small></span><ChevronRight className="row-chevron" /></Button>
}
function HistoryView({ records, items, onAdd, onEdit, onDelete }: { records: MaintenanceRecord[]; items: MaintenanceItem[]; onAdd: () => void; onEdit: (record: MaintenanceRecord) => void; onDelete: (record: MaintenanceRecord) => void }) {
  const sorted = [...records].sort((a, b) => b.performedDate.localeCompare(a.performedDate))
  return <section className="content-stack"><div className="section-heading"><div><h2>Maintenance history</h2><p>Every service, repair, and inspection in one timeline.</p></div><Button variant="outline" onClick={onAdd}><Plus /> Add entry</Button></div><Card className="history-card"><CardContent>{sorted.length ? sorted.map((record) => { const item = items.find((entry) => entry.id === record.itemId); return <div className="history-row" key={record.id}><div className="history-date"><strong>{new Date(`${record.performedDate}T12:00:00`).toLocaleDateString('en-MY', { day: '2-digit' })}</strong><span>{new Date(`${record.performedDate}T12:00:00`).toLocaleDateString('en-MY', { month: 'short', year: 'numeric' })}</span></div><div className="history-copy"><strong>{item?.name ?? 'Maintenance'}</strong><span>{record.odometerKm.toLocaleString()} km{record.provider ? ` · ${record.provider}` : ''}</span>{record.notes && <small>{record.notes}</small>}</div><div className="history-cost">{formatMoney(record.costSen)}</div><DropdownMenu><DropdownMenuTrigger render={<Button variant="ghost" size="icon" aria-label={`Actions for ${item?.name ?? 'entry'}`} />}><Ellipsis /></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={() => onEdit(record)}><Pencil /> Edit</DropdownMenuItem><DropdownMenuItem variant="destructive" onClick={() => onDelete(record)}><Trash2 /> Delete</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div> }) : <div className="empty-history"><HistoryIcon /><h3>No entries yet</h3><p>Log your first service to start a trustworthy maintenance timeline.</p><Button onClick={onAdd}><Plus /> Log maintenance</Button></div>}</CardContent></Card></section>
}

function SettingsView({ bike, items, userId, motorcycleId, onSaved }: { bike: Motorcycle; items: MaintenanceItem[]; userId: string; motorcycleId: string; onSaved: (bike: Motorcycle, items: MaintenanceItem[]) => void }) {
  const [draftBike, setDraftBike] = useState(bike), [draftItems, setDraftItems] = useState(items), [saving, setSaving] = useState(false)
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); try { await Promise.all([saveMotorcycle(userId, motorcycleId, draftBike), ...draftItems.map((item) => saveItem(item.id, item))]); onSaved(draftBike, draftItems); toast.success('Settings saved', { description: 'Your motorcycle and intervals are up to date.' }) } catch (error) { toast.error('Could not save settings', { description: error instanceof Error ? error.message : 'Try again.' }) } finally { setSaving(false) } }
  return <form className="settings-layout" onSubmit={submit}><div><h2>Settings</h2><p>Update your motorcycle and service schedule.</p></div><Card><CardHeader><CardTitle>Motorcycle profile</CardTitle><CardDescription>Used to calculate what is due and when.</CardDescription></CardHeader><CardContent className="settings-grid"><FieldInput id="bike-name" label="Display name" value={draftBike.name} onChange={(value) => setDraftBike({ ...draftBike, name: value })} wide /><FieldInput id="make" label="Make" value={draftBike.make} onChange={(value) => setDraftBike({ ...draftBike, make: value })} /><FieldInput id="model" label="Model" value={draftBike.model} onChange={(value) => setDraftBike({ ...draftBike, model: value })} /><div className="field"><Label htmlFor="start-date">Tracking since</Label><Input id="start-date" type="date" value={draftBike.startDate} onChange={(event) => setDraftBike({ ...draftBike, startDate: event.target.value })} /></div><div className="field"><Label htmlFor="odometer">Current odometer (km)</Label><Input id="odometer" type="number" min="0" value={draftBike.currentOdometerKm} onChange={(event) => setDraftBike({ ...draftBike, currentOdometerKm: Math.max(0, Number(event.target.value)) })} required /></div></CardContent></Card><Card><CardHeader><CardTitle>Service intervals</CardTitle><CardDescription>Press Enter or use Save changes when you’re done.</CardDescription></CardHeader><CardContent className="interval-list">{draftItems.filter((item) => item.basis !== 'condition').map((item) => <div className="interval-row" key={item.id}><span><strong>{item.name}</strong><small>{item.basis === 'time' ? 'Time-based service' : 'Distance-based service'}</small></span><div><Input aria-label={`${item.name} interval`} type="number" min="1" value={item.basis === 'time' ? item.intervalMonths : item.intervalKm} onChange={(event) => setDraftItems((current) => current.map((entry) => entry.id === item.id ? { ...entry, [entry.basis === 'time' ? 'intervalMonths' : 'intervalKm']: Math.max(1, Number(event.target.value)) } : entry))} /><span>{item.basis === 'time' ? 'months' : 'km'}</span></div></div>)}</CardContent></Card><div className="settings-actions"><Button type="submit" size="lg" disabled={saving}>{saving ? 'Saving…' : <><Check /> Save changes</>}</Button></div></form>
}
function FieldInput({ id, label, value, onChange, wide }: { id: string; label: string; value: string; onChange: (value: string) => void; wide?: boolean }) { return <div className={`field${wide ? ' field-wide' : ''}`}><Label htmlFor={id}>{label}</Label><Input id={id} value={value} onChange={(event) => onChange(event.target.value)} required /></div> }

function LogDialog({ open, target, items, bike, onOpenChange, onSave }: { open: boolean; target: LogTarget; items: MaintenanceItem[]; bike: Motorcycle; onOpenChange: (open: boolean) => void; onSave: (record: MaintenanceRecord) => Promise<void> }) {
  const original = target.record
  const [itemId, setItemId] = useState(target.itemId), [date, setDate] = useState(original?.performedDate ?? today), [km, setKm] = useState(String(original?.odometerKm ?? bike.currentOdometerKm)), [cost, setCost] = useState(original?.costSen == null ? '' : String(original.costSen / 100)), [provider, setProvider] = useState(original?.provider ?? ''), [notes, setNotes] = useState(original?.notes ?? ''), [saving, setSaving] = useState(false)
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); try { await onSave({ id: original?.id ?? crypto.randomUUID(), itemId, performedDate: date, odometerKm: Math.max(0, Number(km)), costSen: cost === '' ? undefined : Math.round(Number(cost) * 100), provider: provider.trim() || undefined, notes: notes.trim() || undefined }) } catch (error) { toast.error('Could not save this entry', { description: error instanceof Error ? error.message : 'Try again.' }); setSaving(false) } }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="log-dialog" showCloseButton={false}><form onSubmit={submit}><DialogHeader><div className="dialog-heading"><span className="dialog-icon"><Wrench /></span><div><DialogTitle>{original ? 'Edit maintenance' : 'Log maintenance'}</DialogTitle><DialogDescription>{original ? 'Update this entry and save it to Supabase.' : 'Add the work completed on your motorcycle.'}</DialogDescription></div><DialogClose render={<Button variant="ghost" size="icon" type="button" aria-label="Close" />}><X /></DialogClose></div></DialogHeader><div className="dialog-fields"><div className="field"><Label>Maintenance item</Label><Select value={itemId} onValueChange={(value) => value && setItemId(value)} disabled={Boolean(original)}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{items.map((item) => <SelectItem key={item.id} value={item.id}>{item.name}</SelectItem>)}</SelectContent></Select></div><div className="dialog-grid"><div className="field"><Label htmlFor="performed-date"><CalendarDays /> Date performed</Label><Input id="performed-date" type="date" max={today} value={date} onChange={(event) => setDate(event.target.value)} required /></div><div className="field"><Label htmlFor="record-odometer"><Gauge /> Odometer (km)</Label><Input id="record-odometer" type="number" min="0" value={km} onChange={(event) => setKm(event.target.value)} required /></div></div><div className="dialog-grid"><div className="field"><Label htmlFor="cost">Cost (RM)</Label><Input id="cost" type="number" min="0" step="0.01" value={cost} onChange={(event) => setCost(event.target.value)} placeholder="Optional" /></div><div className="field"><Label htmlFor="provider">Workshop / provider</Label><Input id="provider" value={provider} onChange={(event) => setProvider(event.target.value)} placeholder="Optional" /></div></div><div className="field"><Label htmlFor="notes">Notes</Label><Textarea id="notes" value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Parts used, observations, or anything worth remembering" /></div></div><DialogFooter><DialogClose render={<Button variant="outline" type="button" />}>Cancel</DialogClose><Button type="submit" disabled={saving}>{saving ? 'Saving…' : <><Check /> {original ? 'Save changes' : 'Save record'}</>}</Button></DialogFooter></form></DialogContent></Dialog>
}
function DeleteDialog({ record, item, onOpenChange, onConfirm }: { record: MaintenanceRecord | null; item?: MaintenanceItem; onOpenChange: (open: boolean) => void; onConfirm: () => void }) { return <AlertDialog open={Boolean(record)} onOpenChange={onOpenChange}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete this maintenance entry?</AlertDialogTitle><AlertDialogDescription>{item?.name ?? 'This entry'} will be permanently removed from your Supabase history. This cannot be undone.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep entry</AlertDialogCancel><AlertDialogAction variant="destructive" onClick={onConfirm}><Trash2 /> Delete entry</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog> }
export default App
